version: '3'

services:
    golang:
        #image: restapi-crud_golang
        build: .
        restart: always
        ports:
            - '80:80'
        volumes:
            - /home/ubuntu/githubproy/golang_practices/restapi-crud/app:/app